version: 2
updates:
  - package-ecosystem: "pip"
    directory: "requirements/"
    schedule:
      interval: "monthly"
    groups:
      all-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "build"
