repos:
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.4
  hooks:
    - id: ruff-check
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  exclude: tests/test_table_writer.py
  hooks:
  - id: check-merge-conflict
    exclude: tests/test_table_writer.py
  - id: debug-statements
    exclude: tests/test_table_writer.py
  - id: check-yaml
    exclude: tests/test_table_writer.py
  - id: trailing-whitespace
    exclude: tests/test_table_writer.py


- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  -   id: blacken-docs
      additional_dependencies: [black==22.12.0]

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.5.2
  hooks:
  - id: add-license-headers
    exclude: ^tests/assets/.*$
    args:
    - --start_year=2022

- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.22.0
  hooks:
    - id: zizmor